version: '3.8'

services:
  slimlytics:
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SALT=change-this-salt-value
    restart: unless-stopped