import { AbsoluteFill, Html5Audio, interpolate, staticFile, useCurrentFrame, useVideoConfig } from 'remotion';
import { linearTiming, TransitionSeries } from '@remotion/transitions';
import { fade } from '@remotion/transitions/fade';
import { slide } from '@remotion/transitions/slide';
import { Agents, CallToAction, Dashboard, Deploy, Intro, Privacy, Spy } from './scenes';
import { colors } from './theme';
import { PROMO_FRAMES, SCENES, TRANSITION } from './timeline';

// Scene lengths live in timeline.ts so the soundtrack can use the same timings.
const components = { intro: Intro, privacy: Privacy, spy: Spy, dashboard: Dashboard, agents: Agents, deploy: Deploy, cta: CallToAction };
export const scenes = SCENES.map((scene) => ({ component: components[scene.id], frames: scene.frames }));
export { PROMO_FRAMES };

function Progress() {
  const frame = useCurrentFrame();
  const { durationInFrames } = useVideoConfig();
  return (
    <div
      style={{
        position: 'absolute',
        left: 0,
        bottom: 0,
        height: 6,
        width: `${interpolate(frame, [0, durationInFrames - 1], [0, 100])}%`,
        background: `linear-gradient(90deg, ${colors.glow}, ${colors.blue})`
      }}
    />
  );
}

export function Promo() {
  const timing = linearTiming({ durationInFrames: TRANSITION });
  return (
    <AbsoluteFill style={{ background: colors.ink }}>
      <TransitionSeries>
        {scenes.flatMap(({ component: Scene, frames }, index) => {
          const items = [
            <TransitionSeries.Sequence key={`scene-${index}`} durationInFrames={frames}>
              <Scene />
            </TransitionSeries.Sequence>
          ];
          if (index < scenes.length - 1) {
            items.push(
              <TransitionSeries.Transition
                key={`transition-${index}`}
                presentation={index % 2 ? fade() : slide({ direction: 'from-right' })}
                timing={timing}
              />
            );
          }
          return items;
        })}
      </TransitionSeries>
      <Progress />
      {/* Generated by scripts/compose-audio.mjs (npm run audio) from the same timeline. */}
      <Html5Audio src={staticFile('promo-audio.wav')} />
    </AbsoluteFill>
  );
}
